---
- name: Process Mikrotik configs into clean directory
  hosts: localhost
  gather_facts: no
  vars:
    backup_root: "/tmp/mikrotik-backups"
    clean_root: "{{ backup_root }}/clean"

  tasks:
    - name: Find all Mikrotik configs
      ansible.builtin.find:
        paths: "{{ backup_root }}"
        patterns: "*.rsc"
        recurse: yes
        excludes: "*-clean"
      register: mikrotik_confs

    - name: Ensure clean host-specific directories exist
      ansible.builtin.file:
        path: "{{ clean_root }}/{{ item.path | dirname | basename }}"
        state: directory
      loop: "{{ mikrotik_confs.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Create clean configs without headers
      ansible.builtin.shell: |
        grep -v -E '^(#|[0-9]{4}-[0-9]{2}-[0-9]{2}.*by RouterOS|software id|model =|serial number)' "{{ item.path }}"
        > "{{ clean_root }}/{{ item.path | dirname | basename }}/{{ item.path | basename }}-clean"
      loop: "{{ mikrotik_confs.files }}"
      loop_control:
        label: "{{ item.path }}"
