---
- name: Encrypt Mikrotik configs
  hosts: localhost
  gather_facts: no
  vars:
    backup_root: "/tmp/mikrotik-backups"
  tasks:
    - name: Find original configs
      ansible.builtin.find:
        paths: "{{ backup_root }}"
        patterns: "*.rsc"
        recurse: yes
        excludes: "*-clean"
      register: mikrotik_confs

    - name: Encrypt with ansible-vault
      ansible.builtin.command:
        cmd: ansible-vault encrypt --vault-password-file /etc/ansible/vault.pass "{{ item.path }}"
      loop: "{{ mikrotik_confs.files }}"
      register: vault_encrypt
      failed_when: vault_encrypt.rc != 0 and 'already encrypted' not in vault_encrypt.stderr
